name: "size"

on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on:
      [
        self-hosted,
        ubuntu-latest,
        windows-latest,
        windows-2022,
        macos-11,
        macos-latest,
      ]
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
